### ISSUE TITLE
Creación de los demás formularios (registrar tipos de usuarios)

### ISSUE THREAD

**Issue by SFenrir20** [SFenrir20/LeeMAss_Soft2#1]
Por favor hacer esta tarea porque necesito avanzar.

**Comment by SFenrir20** [comment]
los formularios serian: 
- registrar Usuarios (crud y una tabla)
- registrar Libros (crud y una tabla)
- registra Categorías (Libros) (crud y una tabla)
- registra Tipos de usuarios (crud y una tabla)
- mostrar las ventas (tabla y buscar por fecha e id)
- la ventana de venta 
-  registrar Cliente(crud y una tabla)

**Comment by Dan1409** [comment]
Se realizaron los formularios, falta ventas, revisión de los formular y diseño
